name: General Bug Report
description: "Can you see an issue with the app, that doesn't relate to a specific marker? Use this template."
title: 'Bug: TITLE_YOUR_BUG'
labels: ['bug']
assignees:
  - Odinnh
  - sol3uk
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve our app! 
        Please try and describe the bug in as much detail as possible, screenshots and mockup/sketches are much appreciated but not required.
  - type: textarea
    id: bugDescription
    attributes:
      label: Description
      description: Please tell us the issue you are experiencing.
    validations:
      required: true
